name: deploy
on:
  push:
    branches: [main]

jobs:
  release:
    name: Build and deploy for new release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-node 
        uses: actions/setup-node@v3
        
        with:
          node-version: 14.x
          cache: npm
        
      - name: pull main
        run: git pull origin main
         
      - name: yarn install
        run: yarn install

      - name: chmod bash script
      - run: chmod +x ./pm2_runner.sh


      - name: run bash script
      - run: bash ./scripts/pm2_runner.sh

